### PR TITLE
fix plugin name in README

### PR DESCRIPTION
**Pull request by yct21**

### CODE REVIEW

**Comment by Koolstr** [comment]
This fix is necessary. I was confused why it wasn't working until I noticed the inconsistency. Merge this already please; save others the trouble and time consumption.

**Comment by blakek** [comment]
@yct21 thanks for the PR!  I was clearly not paying attention when making the readme.

**Comment by Koolstr** [comment]
Thanks for the quick merge. I presume you simply forgot to do it earlier?

**Comment by blakek** [comment]
@Koolstr Yep.  I typically read notifications on my phone and they're gone after that.  It'd be nice if there was a way of keeping certain GitHub notifications from disappearing until something's been done.

**Comment by Koolstr** [comment]
i definitely don't blame you. I've just been subject to this exact problem myself, when trying to get back to this thread. XD

**Pull request merged**
